### ISSUE TITLE
Outdated 'sdkbase' directory

### ISSUE THREAD

**Issue by ialarmedalien** [kbase/kb_sdk#351]
The contents of the `sdkbase` directory have been replaced by https://github.com/kbase/sdkbase2. The `sdkbase` directory should be removed, and references to it in the SDK codebase and docs updated to refer to the current GitHub repo and Docker images. The Dockerfile generated in new projects already uses the more up-to-date SDK base image, so having the remnants of the old system hanging around is just confusing.

**Comment by jayrbolton** [comment]
:+1:

**Comment by ialarmedalien** [comment]
See also https://github.com/kbase/kb_sdk_docs/pull/55 -- update to docs to remove the references to manually building the sdkbase image.
